require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1.2
  
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50

Layout/LineLength:
  Max: 150

Naming/MethodParameterName:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
